# Project metadata 
---
title: Wikistream
year: 2012
date_added: 
url: http://wikistream.wmflabs.org/
image:
description: >
    "Wikistream is a Node.js webapp for helping visualize current
    editing activity in Wikipedia. It uses Node.js, socket.io and Redis to sit
    in the wikimedia IRC chat rooms (where updates are published), and makes
    them available on the Web in realtime."
authors:
- {name: Ed Summers, url: https://twitter.com/edsu}
- {name: Sean Hannan, url: https://twitter.com/mrdys}
- {name: Delphine Ménard, url: https://twitter.com/notafish}
code: https://github.com/edsu/wikistream
data_type:
- recent changes
- user contributions
- article revisions
data_source: 
- IRC feeds
